### PR TITLE
Import OBS package content into git.

### PR DESCRIPTION
**Pull request by thorstenb**
See obs-git-import -h for usage. Requires git-fast-import.

### CODE REVIEW

**Comment by aspiers** [comment]
I think this maybe duplicates https://www.gitorious.org/opensuse/bsgit/source/36d57ea663400516805b990a733af11a4292e723:doc ?

**Comment by thorstenb** [comment]
Gah. Yep, your reference is a huge superset of my script.

Are you/is anyone actively using it? Does it work?

(and of course c.f. recent internal discussions ...)

**Comment by aspiers** [comment]
Don't know if anyone is using it.  I started packaging it but never tried it, IIRC.

**Comment by thorstenb** [comment]
well then whatever - the script at hand works for one-off conversions, the project you reference potentially works continuously.

Having all of a legacy OBS repo inside git is just very, very useful when facing the challenge to consolidate several branches, and/or (as this comes from) merge with an independent upstream that's always been inside git.

So _one_ of the two projects should _really_ be included somewhat more prominently in the opensuse toolchain. ;)

**Comment by aspiers** [comment]
I don't understand how you can mix a git repo representing an OBS package's contents, with a git repo representing the upstream source?  One will contain the `.spec`, `.changes`, and a tarball, whereas the other will contain source.

**Comment by thorstenb** [comment]
For the case at hand - both contain spec files. ;)

**Comment by aspiers** [comment]
Yeah but both don't contain tarballs?

**Comment by thorstenb** [comment]
So?

**Comment by aspiers** [comment]
You said "and/or (as this comes from) merge with an independent upstream that's always been inside git".  I fail to see how it is possible to merge a downstream repo which contains source code inside a tarball with an upstream which doesn't.

**Comment by aspiers** [comment]
For the record, `bsgit` has moved here: https://github.com/opensuse/bsgit

**Pull request merged**
